import argparse
import textwrap


def parser():
    description = """\
    This program trains a Multilayer Perceptron (MLP) using a previously
    prepared training dataset generated by the split_data.py script.

    The program accepts two optional arguments:

    1. The name to the .pkl file containing the training dataset.
    2. The name to the .json configuration file describing the neural
       network architecture and training parameters.

    If no dataset path is provided, the program defaults to training_data.pkl.
    All training data must be located inside the "../splitted_data/" directory
    relative to the script's location.

    If no configuration file is provided, or if specific parameters within 
    the file are missing or invalid, the program intelligently falls back to 
    safe default values on a parameter-by-parameter basis, ensuring the 
    training can always execute.

    The absolute global defaults (used if the JSON is empty or missing) are:
    - Input Layer Activation: sigmoid
    - Hidden Layers: 2 layers with 24 neurons each, using sigmoid and heUniform
    - Output Layer Initializer: heUniform
    - Training: 100 epochs, batch_size 16, learning_rate 0.01, loss categorical_crossentropy
    - Optimizer: sgd (Adam defaults: beta1=0.9, beta2=0.999)
    - Early Stopping: enabled, patience 10, monitor val_loss

    All configuration files must be located inside the ../configs/ directory
    relative to the script's location.

    The input layer size is automatically determined by the number of
    features in the dataset (30 features excluding the target variable in this 
    project). The design explicitly allows customization of both the input and
    output layers: the input layer supports configurable activation functions,
    while the output layer supports configurable initialization, while always
    using a fixed softmax activation over two neurons for binary classification.

    Configuration file example:

    {
      "model_name": "breast_cancer_mlp",
      "topology": {
        "input_layer_activation": "sigmoid",
        "hidden_layers": [
          { "n_neurons": 32, "activation": "relu", "initializer": "heUniform" },
          { "n_neurons": 24, "activation": "tanh", "initializer": "xavier" },
          { "n_neurons": 16, "activation": "sigmoid", "initializer": "heNormal" }
        ],
        "output_layer_initializer": "heUniform"
      },
      "training": {
        "epochs": 150,
        "batch_size": 16,
        "learning_rate": 0.01,
        "loss": "categorical_crossentropy",
        "optimizer": {
          "type": "adam",
          "params": { "beta1": 0.9, "beta2": 0.999 }
        }
      },
      "early_stopping": {
        "enabled": true,
        "patience": 10,
        "monitor": "val_loss"
      }
    }

    Valid configuration values & Fallback constraints:

    Activation functions (Input & Hidden):
    ["relu", "sigmoid", "tanh"] -> Invalid values fallback to "sigmoid"

    Initializers (Hidden & Output):
    ["heUniform", "heNormal", "xavier", "random"] -> Invalid values fallback to "heUniform"

    Loss functions:
    ["categorical_crossentropy", "mse"] -> Invalid values fallback to "categorical_crossentropy"

    Optimizers:
    ["sgd", "adam"] -> Invalid values fallback to "sgd"

    Adam parameters:
    beta1 ∈ [0.0, 1.0) -> Out of bounds falls back to 0.9
    beta2 ∈ [0.0, 1.0) -> Out of bounds falls back to 0.999

    Topology constraints:
    - If "hidden_layers" is missing or malformed, it falls back to the default 
      architecture (2 layers of 24 neurons).
    - If provided, each hidden layer must define n_neurons ∈ (0, 256]. Values 
      outside this range will trigger a warning and fallback to 24 neurons.

    Training parameters:
    epochs ∈ (0, 1000] -> Out of bounds falls back to 100
    batch_size ≥ 1 and ≤ dataset size -> Out of bounds falls back to 16
    learning rate > 0.0 (recommended ≤ 0.1) -> Out of bounds falls back to 0.01

    Early stopping:
    enabled: boolean -> Invalid types fallback to true
    patience ≥ 1 and < epochs -> Out of bounds falls back to 10
    monitor: ["val_loss", "val_accuracy"] -> Invalid values fallback to "val_loss"
    """
    parser = argparse.ArgumentParser(
        description = textwrap.dedent(description),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--data_name",
        type=str,
        default="training_data.pkl",
        metavar="",
        help="name of trainning datafile (default: training_data.pkl)"
    )
    parser.add_argument(
        "--config_name",
        type=str,
        default=None,
        metavar="",
        help="name of configuration file (default: None)"
    )

    args = parser.parse_args()
    # El return va al inicio. Python evalúa la condición después del 'if'
    return args.data_name, args.config_name
