import argparse
import textwrap


def parser():
    description = """\
    This program trains a Multilayer Perceptron (MLP) using a unified 
    experiment data capsule generated by the split_dataset.py script.

    The program accepts two optional arguments:

    1. The name of the experiment directory containing the dataset capsule.
       The script will automatically target and load the unifed pickle file
       'train_val_\{data_name\}.pkl' inside that folder.
    2. The name of the .json configuration file describing the neural
       network architecture and training parameters.

    If no dataset folder name is provided, the program defaults to 'default'.
    All experiment directories must be located inside the "../splitted_data/"
    directory relative to the script's location.

    The validation dataset inside the capsule is actively used during the 
    training process to monitor generalization loss and accuracy at the end 
    of each epoch, as well as to trigger the Early Stopping mechanism 
    coherently based on the configured patience.

    If no configuration file is provided, or if specific parameters within 
    the file are missing or invalid, the program intelligently falls back to 
    safe default values on a parameter-by-parameter basis, ensuring the 
    training can always execute.

    The absolute global defaults (used if the JSON is empty or missing) are:
    - Input Layer: raw features forwarded directly to the first hidden layer
    - Hidden Layers: 2 layers with 24 neurons each, using relu and heUniform
    - Output Layer Initializer: xavier
    - Training: 100 epochs, batch_size 16, learning_rate 0.01, loss categorical_crossentropy
    - Optimizer: sgd (Adam defaults: beta1=0.9, beta2=0.999)
    - Early Stopping: enabled, patience 10, monitor val_loss

    All configuration files must be located inside the ../configs/ directory
    relative to the script's location.

    The input features are determined automatically by the dataset shape
    (30 features excluding the target variable in this project). The design
    explicitly treats the input as raw features only: there is no separate
    input-layer activation or initializer. The output layer supports
    configurable initialization while always using a fixed softmax activation
    over two neurons for binary classification.

    Configuration file example:
    {
      "model_name": "breast_cancer_mlp",
      "topology": {
        "hidden_layers": [
          { "n_neurons": 32, "activation": "relu", "initializer": "heUniform" },
          { "n_neurons": 12, "activation": "relu", "initializer": "heNormal" }
        ],
        "output_layer_initializer": "xavier"
      },
      "training": {
        "epochs": 150,
        "batch_size": 16,
        "learning_rate": 0.01,
        "loss": "categorical_crossentropy",
        "optimizer": {
          "type": "adam",
          "params": { "beta1": 0.9, "beta2": 0.999 }
        }
      },
      "early_stopping": {
        "enabled": true,
        "patience": 10,
        "monitor": "val_loss"
      }
    }

    Valid configuration values & Fallback constraints:

    Activation functions (Hidden):
    ["relu", "sigmoid", "tanh"] -> Invalid values fallback to "relu"

    Initializers (Hidden & Output):
    ["heUniform", "heNormal", "xavier", "random"] -> Invalid values fallback to "heUniform"

    Loss functions:
    ["categorical_crossentropy", "mse"] -> Invalid values fallback to "categorical_crossentropy"

    Optimizers:
    ["sgd", "adam"] -> Invalid values fallback to "sgd"

    Adam parameters:
    beta1 ∈ [0.0, 1.0) -> Out of bounds falls back to 0.9
    beta2 ∈ [0.0, 1.0) -> Out of bounds falls back to 0.999

    Topology constraints:
    - If "hidden_layers" is missing or malformed, it falls back to the default 
      architecture (2 layers of 24 neurons).
    - If provided, each hidden layer must define n_neurons ∈ (0, 256]. Values 
      outside this range will trigger a warning and fallback to 24 neurons.

    Training parameters:
    epochs ∈ (0, 1000] -> Out of bounds falls back to 100
    batch_size ≥ 1 and ≤ dataset size -> Out of bounds falls back to 16
    learning rate > 0.0 (recommended ≤ 0.1) -> Out of bounds falls back to 0.01

    Early stopping:
    enabled: boolean -> Invalid types fallback to true
    patience ≥ 1 and < epochs -> Out of bounds falls back to 10
    monitor: ["val_loss", "val_accuracy"] -> Invalid values fallback to "val_loss"
    """
    parser = argparse.ArgumentParser(
        description=textwrap.dedent(description),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    # Cambiado para recibir un único string que representa la carpeta del experimento
    parser.add_argument(
        "-d", "--data_name",
        type=str,
        default="default",
        metavar="",
        help="name of the experiment folder containing the data capsule (default: 'default')"
    )
    parser.add_argument(
        "-c", "--config_name",
        type=str,
        default=None,
        metavar="",
        help="name of configuration file (default: None)"
    )

    args = parser.parse_args()
    
    return args.data_name.strip(), args.config_name