import argparse
import textwrap


def parser():
    description = """\
    This program trains a Multilayer Perceptron (MLP) using a previously
    prepared training dataset and validation dataset generated by the split_data.py script.

    The program accepts two optional arguments:

    1. The names of the .pkl files containing the datasets (Training and Validation).
       If provided, you must pass exactly two files: the first one for training
       and the second one for validation.
    2. The name to the .json configuration file describing the neural
       network architecture and training parameters.

    If no dataset names are provided, the program defaults to:
    ('training_data.pkl', 'validation_data.pkl').
    All training and validation data must be located inside the "../splitted_data/"
    directory relative to the script's location.

    The validation dataset is actively used during the training process to monitor 
    generalization loss and accuracy at the end of each epoch, as well as to trigger 
    the Early Stopping mechanism coherently based on the configured patience.

    If no configuration file is provided, or if specific parameters within 
    the file are missing or invalid, the program intelligently falls back to 
    safe default values on a parameter-by-parameter basis, ensuring the 
    training can always execute.

    The absolute global defaults (used if the JSON is empty or missing) are:
    - Input Layer: raw features forwarded directly to the first hidden layer
    - Hidden Layers: 2 layers with 24 neurons each, using relu and heUniform
    - Output Layer Initializer: xavier
    - Training: 100 epochs, batch_size 16, learning_rate 0.01, loss categorical_crossentropy
    - Optimizer: sgd (Adam defaults: beta1=0.9, beta2=0.999)
    - Early Stopping: enabled, patience 10, monitor val_loss

    All configuration files must be located inside the ../configs/ directory
    relative to the script's location.


    The input features are determined automatically by the dataset shape
    (30 features excluding the target variable in this project). The design
    explicitly treats the input as raw features only: there is no separate
    input-layer activation or initializer. The output layer supports
    configurable initialization while always using a fixed softmax activation
    over two neurons for binary classification.

    Configuration file example:
    {
      "model_name": "breast_cancer_mlp",
      "topology": {
        "hidden_layers": [
          { "n_neurons": 32, "activation": "relu", "initializer": "heUniform" },
          { "n_neurons": 12, "activation": "relu", "initializer": "heNormal" },
          { "n_neurons": 24, "activation": "tanh", "initializer": "xavier" },
          { "n_neurons": 16, "activation": "sigmoid", "initializer": "xavier" }
        ],
        "output_layer_initializer": "xavier"
      },
      "training": {
        "epochs": 150,
        "batch_size": 16,
        "learning_rate": 0.01,
        "loss": "categorical_crossentropy",
        "optimizer": {
          "type": "adam",
          "params": { "beta1": 0.9, "beta2": 0.999 }
        }
      },
      "early_stopping": {
        "enabled": true,
        "patience": 10,
        "monitor": "val_loss"
      }
    }

    Valid configuration values & Fallback constraints:

    Activation functions (Hidden):
    ["relu", "sigmoid", "tanh"] -> Invalid values fallback to "relu"

    Initializers (Hidden & Output):
    ["heUniform", "heNormal", "xavier", "random"] -> Invalid values fallback to "heUniform"

    Loss functions:
    ["categorical_crossentropy", "mse"] -> Invalid values fallback to "categorical_crossentropy"

    Optimizers:
    ["sgd", "adam"] -> Invalid values fallback to "sgd"

    Adam parameters:
    beta1 ∈ [0.0, 1.0) -> Out of bounds falls back to 0.9
    beta2 ∈ [0.0, 1.0) -> Out of bounds falls back to 0.999

    Topology constraints:
    - If "hidden_layers" is missing or malformed, it falls back to the default 
      architecture (2 layers of 24 neurons).
    - If provided, each hidden layer must define n_neurons ∈ (0, 256]. Values 
      outside this range will trigger a warning and fallback to 24 neurons.

    Training parameters:
    epochs ∈ (0, 1000] -> Out of bounds falls back to 100
    batch_size ≥ 1 and ≤ dataset size -> Out of bounds falls back to 16
    learning rate > 0.0 (recommended ≤ 0.1) -> Out of bounds falls back to 0.01

    Early stopping:
    enabled: boolean -> Invalid types fallback to true
    patience ≥ 1 and < epochs -> Out of bounds falls back to 10
    monitor: ["val_loss", "val_accuracy"] -> Invalid values fallback to "val_loss"
    """
    parser = argparse.ArgumentParser(
        description=textwrap.dedent(description),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    # Cambiado a nargs="+" para recibir una lista de archivos
    parser.add_argument(
        "-d", "--data_name",
        type=str,
        nargs="+",
        default=["training_data.pkl", "validation_data.pkl"],
        metavar="",
        help="names of training and validation files (default: training_data.pkl validation_data.pkl)"
    )
    parser.add_argument(
        "-c", "--config_name",
        type=str,
        default=None,
        metavar="",
        help="name of configuration file (default: None)"
    )

    args = parser.parse_args()
    
    # Validación manual para asegurar que si el usuario ingresa archivos, ingrese exactamente dos
    if len(args.data_name) != 2:
        parser.error("You must provide exactly two files for --data_name: [training_file] [validation_file]")

    # Retorna data_name como una tupla (train, val) y el config_name
    return tuple(args.data_name), args.config_name